from __future__ import annotations

import json
import logging
import os
import re
from typing import Any

import requests


LOGGER = logging.getLogger(__name__)


class LLMClient:
    """
    Safe Ollama client.

    Existing compatibility:
    - generate(prompt) still returns plain text.
    - The global `llm` object remains available.

    New functionality:
    - generate_json(prompt) returns structured JSON.
    - JSON generation does not use the normal text fallback.
    - Invalid or unavailable JSON generation raises a controlled error so
      the GitOps engine can return MANUAL_INVESTIGATION_REQUIRED.
    """

    def __init__(
        self,
        base_url: str | None = None,
        model: str | None = None,
        timeout_seconds: int | None = None,
    ) -> None:
        self.base_url = (
            base_url
            or os.getenv(
                "OLLAMA_BASE_URL",
                "http://localhost:11434",
            )
        ).rstrip("/")

        self.model = (
            model
            or os.getenv(
                "OLLAMA_MODEL",
                "qwen2.5:1.5b",
            )
        )

        configured_timeout = (
            timeout_seconds
            or int(
                os.getenv(
                    "OLLAMA_TIMEOUT_SECONDS",
                    "180",
                )
            )
        )

        self.timeout = (
            10,
            configured_timeout,
        )

        self.num_ctx = int(
            os.getenv(
                "OLLAMA_NUM_CTX",
                "4096",
            )
        )

    def _fallback_response(
        self,
        error: str,
    ) -> str:
        return f"""
## LLM Availability Notice

The local language model was unavailable while processing this incident.

Error:

`{error}`

## Evidence-Safe Result

No new root-cause claim has been generated by the language model.

Use the deterministic Kubernetes, Prometheus, Loki, restart-history,
alert-assessment, and validation evidence already collected by the workflow.

## Required Action

Continue in recommendation-only mode.

Do not create or execute a configuration change solely from this fallback
response.

The incident may proceed only when the deterministic GitOps strategy has
independently confirmed:

- the affected workload;
- the failing configuration;
- the exact repository path;
- the proposed before-and-after content;
- deterministic validation;
- human approval.
""".strip()

    def health(self) -> dict[str, Any]:
        try:
            response = requests.get(
                f"{self.base_url}/api/tags",
                timeout=(5, 15),
            )
            response.raise_for_status()

            payload = response.json()

            return {
                "available": True,
                "base_url": self.base_url,
                "model": self.model,
                "models": payload.get(
                    "models",
                    [],
                ),
                "error": None,
            }

        except (
            requests.RequestException,
            ValueError,
        ) as error:
            return {
                "available": False,
                "base_url": self.base_url,
                "model": self.model,
                "models": [],
                "error": str(error),
            }

    def _call_generate(
        self,
        *,
        prompt: str,
        temperature: float,
        json_mode: bool,
    ) -> str:
        if not isinstance(
            prompt,
            str,
        ):
            raise TypeError(
                "The LLM prompt must be a string."
            )

        if not prompt.strip():
            raise ValueError(
                "The LLM prompt cannot be empty."
            )

        payload: dict[str, Any] = {
            "model": self.model,
            "prompt": prompt,
            "stream": False,
            "options": {
                "temperature": temperature,
                "num_ctx": self.num_ctx,
            },
        }

        if json_mode:
            payload["format"] = "json"

        LOGGER.info(
            "Calling Ollama: model=%s url=%s json_mode=%s",
            self.model,
            self.base_url,
            json_mode,
        )

        response = requests.post(
            f"{self.base_url}/api/generate",
            json=payload,
            timeout=self.timeout,
        )

        if not response.ok:
            response_text = (
                response.text
                or "<empty response>"
            )

            raise RuntimeError(
                "Ollama returned HTTP "
                f"{response.status_code}: "
                f"{response_text[:1000]}"
            )

        try:
            data = response.json()
        except ValueError as error:
            raise RuntimeError(
                "Ollama returned a non-JSON API response."
            ) from error

        generated_text = str(
            data.get(
                "response",
                "",
            )
        ).strip()

        if not generated_text:
            raise RuntimeError(
                "Ollama returned an empty response."
            )

        return generated_text

    def generate(
        self,
        prompt: str,
    ) -> str:
        """
        Existing plain-text interface used by RCA and chat.

        This method keeps the evidence-safe text fallback so earlier
        workflows do not fail when Ollama is temporarily unavailable.
        """

        try:
            return self._call_generate(
                prompt=prompt,
                temperature=0.1,
                json_mode=False,
            )

        except (
            requests.RequestException,
            RuntimeError,
            ValueError,
            TypeError,
        ) as error:
            LOGGER.exception(
                "Ollama generation failed; using "
                "evidence-safe fallback: %s",
                error,
            )

            return self._fallback_response(
                str(error)
            )

    @staticmethod
    def _strip_markdown_fence(
        value: str,
    ) -> str:
        text = value.strip()

        fenced_match = re.fullmatch(
            r"```(?:json)?\s*(.*?)\s*```",
            text,
            flags=(
                re.IGNORECASE
                | re.DOTALL
            ),
        )

        if fenced_match:
            return fenced_match.group(
                1
            ).strip()

        return text

    @staticmethod
    def _extract_json_object(
        value: str,
    ) -> str:
        """
        Extract the outermost JSON object when a model adds small amounts
        of prose around it.
        """

        text = LLMClient._strip_markdown_fence(
            value
        )

        try:
            json.loads(
                text
            )
            return text
        except json.JSONDecodeError:
            pass

        start = text.find(
            "{"
        )

        end = text.rfind(
            "}"
        )

        if (
            start == -1
            or end == -1
            or end <= start
        ):
            raise ValueError(
                "The LLM response did not contain a JSON object."
            )

        candidate = text[
            start : end + 1
        ]

        json.loads(
            candidate
        )

        return candidate

    def generate_json(
        self,
        prompt: str,
    ) -> dict[str, Any]:
        """
        Generate a strict structured proposal.

        Unlike generate(), this method must never convert an Ollama
        failure into natural-language remediation. The GitOps layer needs
        an explicit exception so it can stop safely.

        Raises:
            RuntimeError:
                Ollama request or response failure.

            ValueError:
                Invalid JSON or a non-object result.
        """

        try:
            generated_text = (
                self._call_generate(
                    prompt=prompt,
                    temperature=0.0,
                    json_mode=True,
                )
            )

            json_text = (
                self._extract_json_object(
                    generated_text
                )
            )

            result = json.loads(
                json_text
            )

            if not isinstance(
                result,
                dict,
            ):
                raise ValueError(
                    "The structured LLM response must be a JSON object."
                )

            return result

        except (
            requests.RequestException,
            RuntimeError,
            ValueError,
            TypeError,
            json.JSONDecodeError,
        ) as error:
            LOGGER.exception(
                "Structured Ollama generation failed: %s",
                error,
            )

            raise RuntimeError(
                "Unable to generate a valid structured remediation "
                f"proposal: {error}"
            ) from error


llm = LLMClient()